language: node_js
node_js:
  - 0.10

notifications:
  email: false

env:
  global:
    secure: "J+r0Q1T34TrOLKTyeRH219XFhdr2jeAMvlWiC9Sx7CenZQJhM4t/O3YvyOGjTIvqSFvgU0EQmbpZlH81FEAzLawpifjqh5hqYwClqhQCfZYFhpBYnu1AX07UFCqPecvJbq5h9WPyehjRqqo+MkEKRrt/cuWP3ffSeTZx4I5mtO8="

after_script:
  - "./node_modules/gulp/bin/gulp.js coveralls"
